"""updated tables

Revision ID: 151cb9b048a7
Revises: 52866405d2e1
Create Date: 2023-08-21 19:44:22.680588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151cb9b048a7'
down_revision = '52866405d2e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('lecture', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('lecture', sa.Column('longitude', sa.Float(), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture', 'longitude')
    op.drop_column('lecture', 'latitude')
    op.drop_column('lecture', 'accuracy')

    # ### end Alembic commands ###
