"""added student table

Revision ID: 2b814d8b64fa
Revises: 5dd251d3ec36
Create Date: 2023-06-06 21:50:21.184806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b814d8b64fa'
down_revision = '5dd251d3ec36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
