"""updated tables

Revision ID: 52866405d2e1
Revises: a4f6615d944f
Create Date: 2023-08-20 23:49:24.429189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52866405d2e1'
down_revision = 'a4f6615d944f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attendance', 'lecture', ['lecture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'attendance', type_='foreignkey')
    # ### end Alembic commands ###
