"""added staffcourse table

Revision ID: 5a2ff620fcd2
Revises: 3675c5e1d222
Create Date: 2023-06-08 20:14:06.827134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2ff620fcd2'
down_revision = '3675c5e1d222'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffcourse',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'course_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffcourse')
    # ### end Alembic commands ###
