"""updated tables

Revision ID: 6ad303300a7f
Revises: 90406ca51501
Create Date: 2023-08-17 22:48:45.495105

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6ad303300a7f'
down_revision = '90406ca51501'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('lecture', sa.Column('lecture_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture', 'lecture_secret')
    
    # ### end Alembic commands ###
