"""added staff table

Revision ID: 90a4ce2bf065
Revises: bdd42ab56247
Create Date: 2023-06-08 17:51:25.250643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a4ce2bf065'
down_revision = 'bdd42ab56247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
