"""added lecture table

Revision ID: 926623b3324a
Revises: b92604205fec
Create Date: 2023-06-08 22:28:58.852840

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '926623b3324a'
down_revision = 'b92604205fec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lecture_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lecture_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture')
    # ### end Alembic commands ###
