"""updated tables

Revision ID: 95291bb8aaad
Revises: c84b20912127
Create Date: 2023-07-15 17:56:17.671249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95291bb8aaad'
down_revision = 'c84b20912127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
