"""updated tables

Revision ID: a4f6615d944f
Revises: 81c0cd341e09
Create Date: 2023-08-20 23:43:35.595940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f6615d944f'
down_revision = '81c0cd341e09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attendance_lecture_id_fkey', 'attendance', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('attendance_lecture_id_fkey', 'attendance', 'lecture', ['lecture_id'], ['id'])
    # ### end Alembic commands ###
