"""added studentcourse table

Revision ID: b92604205fec
Revises: 5a2ff620fcd2
Create Date: 2023-06-08 21:34:33.094048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92604205fec'
down_revision = '5a2ff620fcd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentcourse',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentcourse')
    # ### end Alembic commands ###
