"""test2

Revision ID: dd429295e73c
Revises: 3a50202f00c3
Create Date: 2023-05-22 12:36:15.542696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd429295e73c'
down_revision = '3a50202f00c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
